### ISSUE TITLE
please considering support binary data which is at least 100K bytes and data dilution

### ISSUE THREAD

**Issue by zhanghongquan** [taosdata/TDengine#12203]
**Is your feature request related to a problem? Please describe.**
Background:
  we use vibration sensors installed on rotating machine to collect vibration data -- accelaration data indeed, we call these data as vibration wave data （wave data in short). According to algorithm on our platform,  we can detect if there is a fault on the monitorred machine. if the data show that the machine has some fault, we call the data as fault data, and others are normal data

problems:
1. vibration data collected in one packet is about 100K bytes( 25.6K float), which can not be stored in TDEngine even using binary data type
2. we want to store fault data as long as possible but delete normal data to keep storage usage low.

**Describe your desired behavior**
1. Could TDengine support at least 100K (or could be configured) binary data
2. Could TDengine support data dilution, that is support deleting not-expired data

**Comment by fenghuazzm** [comment]
It is currently supported to delete outdated data using the KEEP parameter, but it can be revealed that a new version will be released this month to support 'delete'，which achieve the deleting of not-expired data you mentioned.
In order to further understand the background of your requirements, you can add my own wechat account to communicate: Deja_vu_4u
