### ISSUE TITLE
10 times faster than hadoop，what  testing scenarios ? 

### ISSUE THREAD

**Issue by MacChen01** [taosdata/TDengine#147]
10 times faster than hadoop，what  testing scenarios ? can you  provide a benchmark for it ?

**Comment by jtao1735** [comment]
We compared TDengine with OpenTSDB. OpenTSDB is based on HBase with time-series data optimization. Please go to taosdata.com to check the full testing report. For one customer in connected vehicles scenario, they replaced kafka + HBase + Redis + Spark + HDFS combination with TDengine, the performance is a big surprise. Storage is only 7%, query is at least 50 times faster. Since   non-disclosure agreement, we could not release its name and testing data. You are welcome to run a testing and share the result with us.
