### ISSUE TITLE
Dedicated type for error code

### ISSUE THREAD

**Issue by haoyifan** [taosdata/TDengine#1807]
While I was reading the code I noticed a lot of functions return a mix of integers, errno from libc and taos error code. Although error code is intrinsically int type, this inconsistency makes code reading harder.

Can you consider typedef an alias for error code, something like:
```
typedef taosCode int32_t
```

And for the functions that are supposed to return taos error code, make it return a type of taosCode instead of ad-hoc returning int/int32_t, etc. This conveys a clearer meaning that this function is supposed to return an error code defined in taoserror.h

**Comment by localvar** [comment]
hmm..., this issue is really embarrassed.

you may already notice there's a macro called `TAOS_SYSTEM_ERROR` in `taoserror.h`, so what we need to do is not define a new `taosCode`, but to using this macro to convert `errno`s to taos error codes, and only use taos error code.
however, this is not followed strictly for some historical and other reasons.

we need an overall fix for this, may some time later.

**Comment by haoyifan** [comment]
beyond this, some functions just return plain "0" to indicate success, while it should just use TSDB_CODE_SUCCESS. I found this issue more prevalent.
