### ISSUE TITLE
pthread_cancel related

### ISSUE THREAD

**Issue by freemine** [taosdata/TDengine#1827]
a few of pthread_cancel calls found in the project, but no corresponding pthread_cleanup_push/pop calls exist in some of the source files, especially in tsched.c, which is believed the fundamental infrastructure component of this project. I am afraid, if some script is triggering to tear-down taosd while the latter is currently busy doing reading/writing on the file system, could the data corruption occur there after? Or, is there any other guarding codes around, that I happen to neglect?

**Comment by localvar** [comment]
thanks for raise this issue.
but seems `pthread_cleanup_push` could not (or very hard to) handle cases like file system writing either, may be we need to implement some graceful method to inform a thread to exit.

**Comment by freemine** [comment]
yes, good practice is not to use pthread_cancel calls.

**Comment by freemine** [comment]
@localvar better add volatile before `bool stop`, cause the variable would be read in the big loop from time to time. keyword volatile helps to prevent compiler optimization from reading it in register.

**Comment by localvar** [comment]
@freemine, if my memory is correct, then when a member variable is accessed through a struct/class pointer, compiler never put it into register, I think I've read something about this before but failed to find the article currently.

another possible issue is memory order because I didn't use `atomic` functions in the read/write of `stop`, but as other functions like `sem_post` / `sem_wait` makes a memory fence, I think it won't become a real problem.

**Comment by localvar** [comment]
close as fixed.
