### ISSUE TITLE
Error of unable to connect the TDengine

### ISSUE THREAD

**Issue by tbluesky2012** [taosdata/TDengine#18306]
In my project,  when I use **upper case database name** to connect the database by  the library **TDengine Connector 3.0.1** , the function  'TDengine.Connect' will return **IntPtr.Zero**. But when use  **lowercase database name**, it will get a success result.

**Comment by xleili** [comment]
Firstly, thank you for your issue.
For the following interface, the parameter "db" will send to taosc (taos client without any change). 
       ` static extern public IntPtr Connect(string ip, string user, string password, string db, short port);`

You got two kinds of responses, since TDengine's database name is case sensitive. For example, database `test` and database `TEST`, they are different databases.

Besides, IntPtr.Zero same as null pointer which means you got null pointer while connecting to you database. Since can connect to TDengine with parameters you just passed.

**Comment by tbluesky2012** [comment]
![image](https://user-images.githubusercontent.com/12482184/202996009-a323656e-4abe-45df-84e9-356f196e8622.png)
But when I  use TDengine Client, TDengine's database name is not case sensitive.

**Comment by sangshuduo** [comment]
> ![image](https://user-images.githubusercontent.com/12482184/202996009-a323656e-4abe-45df-84e9-356f196e8622.png) But when I use TDengine Client, TDengine's database name is not case sensitive.

Yes, connect and query behavior is different by design

**Comment by xleili** [comment]
The basic rule is that in a SQL statement using `` means your SQL statement is case sensitive, on the hand statement without `` means you SQL statement is case insensitive.

1. For the SQL statements being executed in taos-shell, that follows this rule
2. For the SQL statements being executed with Interface `TDengine.Query()` also follow this rule.
3. For the C# connector interface `TDengine.Connect()`, the parameter db is case sensitive. You don't have to send database name with ``, which means "test"="`test`" or "TEST"="`TEST`"
