### ISSUE TITLE
timer library

### ISSUE THREAD

**Issue by haoyifan** [taosdata/TDengine#1851]
When I started reading the timer implementation, I was under the impression that it implemented a hierarchical timer infrastructure where timers with deadline smaller than current wheel's resolution will be demoted to wheel with smaller resolution. This timer implementation idea is popular in the industry (for example, Kafka implements this hierarchical timer). The idea comes from this paper: http://www.cs.columbia.edu/~nahum/w6998/papers/sosp87-timing-wheels.pdf. The reason for me to have this thought is because taos timer library uses some sort of **timer wheel**.

However after I understood how it works, the library actually has several independent timer wheels each with its own resolution. Timers with larger deadline is simply added to the highest wheel, and it could be delayed as large as the resolution of the wheel. In another word, **the resolution of the timer is coupled with the deadline of the timer**. This might or might not be an issue, but current implementation could delay a timer with 1024 seconds deadline to be fired after 1084 seconds...

**Comment by localvar** [comment]
because most OS are not realtime, timers in TDengine are mainly for schedule some background tasks which will be executed later, so they don't need to be very accurate, and the implementation only ensure them not fire earlier as desired but allows some delay.

the use of several timer wheels is a balance of performance and memory, and a min-heap based implementation may be a better choice. however, more things need to be considered for a good timer implementation, for example, where there are many CPU cores, the competition of the timer data structures impact performance very much. these could be improved later.
