### ISSUE TITLE
每次编译都会出现这个错误

### ISSUE THREAD

**Issue by skyformat99** [taosdata/TDengine#19346]
操作顺序如下：
1，git  clone  最新版本的代码
2.  mkdir  debug
3. cd debug     
4. cmake ..

出现如下错误：
[ 82%] Performing update step for 'taosadapter'
fatal: ambiguous argument 'a2e9920': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
来自 https://github.com/taosdata/taosadapter
   5662a6d..a2e9920  3.0        -> origin/3.0
 * [新分支]          fix/sunpeng/TD-21185-taosadapter-vgid-conn-put -> origin/fix/sunpeng/TD-21185-taosadapter-vgid-conn-put
之前的 HEAD 位置是 5662a6d... Merge pull request #127 from taosdata/fix/TS-2282/3.0
HEAD 目前位于 a2e9920... fix: fix table vgid conn pool (#128)

**Comment by sangshuduo** [comment]
我这没有问题

$ cmake ..
-- The C compiler identification is GNU 11.3.0
-- The CXX compiler identification is GNU 11.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Current system: Linux
Current system processor: x86_64
-- Current platform is x86
-- Platform arch:i386
C Compiler: /usr/bin/cc (GNU, 11.3.0)
CXX Compiler: /usr/bin/c++ (GNU, 11.3.0)
-- Project source directory: /home/ubuntu/work/taosdata/TDengine.3
-- Project binary files output path: /home/ubuntu/work/taosdata/TDengine.3/debug
-- Project executable files output path: /home/ubuntu/work/taosdata/TDengine.3/debug/build/bin
-- Project library files output path: /home/ubuntu/work/taosdata/TDengine.3/debug/build/lib
 Will _not_ build taos_tools!
-- Performing Test COMPILER_SUPPORT_SSE42
-- Performing Test COMPILER_SUPPORT_SSE42 - Success
-- Performing Test COMPILER_SUPPORT_FMA
-- Performing Test COMPILER_SUPPORT_FMA - Success
-- Performing Test COMPILER_SUPPORT_AVX
-- Performing Test COMPILER_SUPPORT_AVX - Success
-- Performing Test COMPILER_SUPPORT_AVX2
-- Performing Test COMPILER_SUPPORT_AVX2 - Success
-- ============= compile version parameter information start =============
-- version:    3.0.2.1
-- compatible: 3.0.0.0
-- commit id:  f24703f8b2a0cf5c4cfc5b1a6d32f4976d72efe2
-- build date: 2023-01-04 09:36:57
-- build type:
-- type:       stable
-- cpu:        x64
-- os:         Linux
-- ============= compile version parameter information end  =============
BUILD_HTTP is off, use taosAdapter
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/work/taosdata/TDengine.3/contrib/deps-download
[  2%] Creating directories for 'taosadapter'
[  4%] Performing download step (git clone) for 'taosadapter'
Cloning into 'taosadapter'...
HEAD is now at a2e9920 fix: fix table vgid conn pool (#128)
[  6%] Performing update step for 'taosadapter'
[  8%] No patch step for 'taosadapter'
[ 11%] No configure step for 'taosadapter'
[ 13%] No build step for 'taosadapter'
[ 15%] No install step for 'taosadapter'
[ 17%] No test step for 'taosadapter'
[ 20%] Completed 'taosadapter'
[ 20%] Built target taosadapter
[ 22%] Creating directories for 'lz4'
[ 24%] Performing download step (git clone) for 'lz4'
Cloning into 'lz4'...
HEAD is now at d443718 Merge branch 'dev' into release
[ 26%] Performing update step for 'lz4'
[ 28%] No patch step for 'lz4'
[ 31%] No configure step for 'lz4'
[ 33%] No build step for 'lz4'
[ 35%] No install step for 'lz4'
[ 37%] No test step for 'lz4'
[ 40%] Completed 'lz4'
[ 40%] Built target lz4
[ 42%] Creating directories for 'zlib'
[ 44%] Performing download step (git clone) for 'zlib'
Cloning into 'zlib'...
HEAD is now at cacf7f1 zlib 1.2.11
[ 46%] Performing update step for 'zlib'
[ 48%] No patch step for 'zlib'
[ 51%] No configure step for 'zlib'
[ 53%] No build step for 'zlib'
[ 55%] No install step for 'zlib'
[ 57%] No test step for 'zlib'
[ 60%] Completed 'zlib'
[ 60%] Built target zlib
[ 62%] Creating directories for 'cjson'
[ 64%] Performing download step (git clone) for 'cjson'
Cloning into 'cJson'...
HEAD is now at d348621 chore: update version and changelog (#610)
[ 66%] Performing update step for 'cjson'
[ 68%] No patch step for 'cjson'
[ 71%] No configure step for 'cjson'
[ 73%] No build step for 'cjson'
[ 75%] No install step for 'cjson'
[ 77%] No test step for 'cjson'
[ 80%] Completed 'cjson'
[ 80%] Built target cjson
[ 82%] Creating directories for 'libuv'
[ 84%] Performing download step (git clone) for 'libuv'
Cloning into 'libuv'...
HEAD is now at 0c1fa696 2022.07.12, Version 1.44.2 (Stable)
[ 86%] Performing update step for 'libuv'
[ 88%] No patch step for 'libuv'
[ 91%] No configure step for 'libuv'
[ 93%] No build step for 'libuv'
[ 95%] No install step for 'libuv'
[ 97%] No test step for 'libuv'
[100%] Completed 'libuv'
[100%] Built target libuv
CMake Deprecation Warning at contrib/cJson/CMakeLists.txt:2 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Performing Test FLAG_SUPPORTED_stdc89
-- Performing Test FLAG_SUPPORTED_stdc89 - Success
-- Performing Test FLAG_SUPPORTED_pedantic
-- Performing Test FLAG_SUPPORTED_pedantic - Success
-- Performing Test FLAG_SUPPORTED_Wall
-- Performing Test FLAG_SUPPORTED_Wall - Success
-- Performing Test FLAG_SUPPORTED_Wextra
-- Performing Test FLAG_SUPPORTED_Wextra - Success
-- Performing Test FLAG_SUPPORTED_Werror
-- Performing Test FLAG_SUPPORTED_Werror - Success
-- Performing Test FLAG_SUPPORTED_Wstrictprototypes
-- Performing Test FLAG_SUPPORTED_Wstrictprototypes - Success
-- Performing Test FLAG_SUPPORTED_Wwritestrings
-- Performing Test FLAG_SUPPORTED_Wwritestrings - Success
-- Performing Test FLAG_SUPPORTED_Wshadow
-- Performing Test FLAG_SUPPORTED_Wshadow - Success
-- Performing Test FLAG_SUPPORTED_Winitself
-- Performing Test FLAG_SUPPORTED_Winitself - Success
-- Performing Test FLAG_SUPPORTED_Wcastalign
-- Performing Test FLAG_SUPPORTED_Wcastalign - Success
-- Performing Test FLAG_SUPPORTED_Wformat2
-- Performing Test FLAG_SUPPORTED_Wformat2 - Success
-- Performing Test FLAG_SUPPORTED_Wmissingprototypes
-- Performing Test FLAG_SUPPORTED_Wmissingprototypes - Success
-- Performing Test FLAG_SUPPORTED_Wstrictoverflow2
-- Performing Test FLAG_SUPPORTED_Wstrictoverflow2 - Success
-- Performing Test FLAG_SUPPORTED_Wcastqual
-- Performing Test FLAG_SUPPORTED_Wcastqual - Success
-- Performing Test FLAG_SUPPORTED_Wundef
-- Performing Test FLAG_SUPPORTED_Wundef - Success
-- Performing Test FLAG_SUPPORTED_Wswitchdefault
-- Performing Test FLAG_SUPPORTED_Wswitchdefault - Success
-- Performing Test FLAG_SUPPORTED_Wconversion
-- Performing Test FLAG_SUPPORTED_Wconversion - Success
-- Performing Test FLAG_SUPPORTED_Wccompat
-- Performing Test FLAG_SUPPORTED_Wccompat - Success
-- Performing Test FLAG_SUPPORTED_fstackprotectorstrong
-- Performing Test FLAG_SUPPORTED_fstackprotectorstrong - Success
-- Performing Test FLAG_SUPPORTED_Wcomma
-- Performing Test FLAG_SUPPORTED_Wcomma - Failed
-- Performing Test FLAG_SUPPORTED_Wdoublepromotion
-- Performing Test FLAG_SUPPORTED_Wdoublepromotion - Success
-- Performing Test FLAG_SUPPORTED_Wparentheses
-- Performing Test FLAG_SUPPORTED_Wparentheses - Success
-- Performing Test FLAG_SUPPORTED_Wformatoverflow
-- Performing Test FLAG_SUPPORTED_Wformatoverflow - Success
-- Performing Test FLAG_SUPPORTED_Wunusedmacros
-- Performing Test FLAG_SUPPORTED_Wunusedmacros - Success
-- Performing Test FLAG_SUPPORTED_Wmissingvariabledeclarations
-- Performing Test FLAG_SUPPORTED_Wmissingvariabledeclarations - Failed
-- Performing Test FLAG_SUPPORTED_Wusedbutmarkedunused
-- Performing Test FLAG_SUPPORTED_Wusedbutmarkedunused - Failed
-- Performing Test FLAG_SUPPORTED_Wswitchenum
-- Performing Test FLAG_SUPPORTED_Wswitchenum - Success
-- Performing Test FLAG_SUPPORTED_fvisibilityhidden
-- Performing Test FLAG_SUPPORTED_fvisibilityhidden - Success
CMake Deprecation Warning at contrib/lz4/build/cmake/CMakeLists.txt:37 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Performing Test CFLAG_Wall
-- Performing Test CFLAG_Wall - Success
-- Performing Test CFLAG_Wextra
-- Performing Test CFLAG_Wextra - Success
-- Performing Test CFLAG_Wundef
-- Performing Test CFLAG_Wundef - Success
-- Performing Test CFLAG_Wcast_qual
-- Performing Test CFLAG_Wcast_qual - Success
-- Performing Test CFLAG_Wcast_align
-- Performing Test CFLAG_Wcast_align - Success
-- Performing Test CFLAG_Wshadow
-- Performing Test CFLAG_Wshadow - Success
-- Performing Test CFLAG_Wswitch_enum
-- Performing Test CFLAG_Wswitch_enum - Success
-- Performing Test CFLAG_Wdeclaration_after_statement
-- Performing Test CFLAG_Wdeclaration_after_statement - Success
-- Performing Test CFLAG_Wstrict_prototypes
-- Performing Test CFLAG_Wstrict_prototypes - Success
-- Performing Test CFLAG_Wpointer_arith
-- Performing Test CFLAG_Wpointer_arith - Success
-- Performing Test CFLAG_W4
-- Performing Test CFLAG_W4 - Failed
CMake Deprecation Warning at contrib/zlib/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of off64_t
-- Check size of off64_t - done
-- Looking for fseeko
-- Looking for fseeko - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Renaming
--     /home/ubuntu/work/taosdata/TDengine.3/contrib/zlib/zconf.h
-- to 'zconf.h.included' because this file is included with zlib
-- but CMake generates it automatically in the build directory.
-- Performing Test UV_LINT_W4
-- Performing Test UV_LINT_W4 - Failed
-- Performing Test UV_LINT_NO_UNUSED_PARAMETER_MSVC
-- Performing Test UV_LINT_NO_UNUSED_PARAMETER_MSVC - Failed
-- Performing Test UV_LINT_NO_CONDITIONAL_CONSTANT_MSVC
-- Performing Test UV_LINT_NO_CONDITIONAL_CONSTANT_MSVC - Failed
-- Performing Test UV_LINT_NO_NONSTANDARD_MSVC
-- Performing Test UV_LINT_NO_NONSTANDARD_MSVC - Failed
-- Performing Test UV_LINT_NO_NONSTANDARD_EMPTY_TU_MSVC
-- Performing Test UV_LINT_NO_NONSTANDARD_EMPTY_TU_MSVC - Failed
-- Performing Test UV_LINT_NO_NONSTANDARD_FILE_SCOPE_MSVC
-- Performing Test UV_LINT_NO_NONSTANDARD_FILE_SCOPE_MSVC - Failed
-- Performing Test UV_LINT_NO_NONSTANDARD_NONSTATIC_DLIMPORT_MSVC
-- Performing Test UV_LINT_NO_NONSTANDARD_NONSTATIC_DLIMPORT_MSVC - Failed
-- Performing Test UV_LINT_NO_HIDES_LOCAL
-- Performing Test UV_LINT_NO_HIDES_LOCAL - Failed
-- Performing Test UV_LINT_NO_HIDES_PARAM
-- Performing Test UV_LINT_NO_HIDES_PARAM - Failed
-- Performing Test UV_LINT_NO_HIDES_GLOBAL
-- Performing Test UV_LINT_NO_HIDES_GLOBAL - Failed
-- Performing Test UV_LINT_NO_CONDITIONAL_ASSIGNMENT_MSVC
-- Performing Test UV_LINT_NO_CONDITIONAL_ASSIGNMENT_MSVC - Failed
-- Performing Test UV_LINT_NO_UNSAFE_MSVC
-- Performing Test UV_LINT_NO_UNSAFE_MSVC - Failed
-- Performing Test UV_LINT_WALL
-- Performing Test UV_LINT_WALL - Success
-- Performing Test UV_LINT_NO_UNUSED_PARAMETER
-- Performing Test UV_LINT_NO_UNUSED_PARAMETER - Success
-- Performing Test UV_LINT_STRICT_PROTOTYPES
-- Performing Test UV_LINT_STRICT_PROTOTYPES - Success
-- Performing Test UV_LINT_EXTRA
-- Performing Test UV_LINT_EXTRA - Success
-- Performing Test UV_LINT_UTF8_MSVC
-- Performing Test UV_LINT_UTF8_MSVC - Failed
-- Performing Test UV_F_STRICT_ALIASING
-- Performing Test UV_F_STRICT_ALIASING - Success
-- summary of build options:
    Install prefix:  /usr/local
    Target system:   Linux
    Compiler:
      C compiler:    /usr/bin/cc (GNU)
      CFLAGS:          -std=gnu99 -Werror -Werror=return-type -fPIC -gdwarf-2 -g3 -Wformat=2 -Wno-format-nonliteral -Wno-format-truncation -Wno-format-y2k -msse4.2


 use original embedded httpd

-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/work/taosdata/TDengine.3/debug

**Comment by yu285** [comment]
暂无反馈，做关闭处理
