### ISSUE TITLE
Failed to start TDengine server service.

### ISSUE THREAD

**Issue by tssunjingwu** [taosdata/TDengine#200]
ERROR MND-SDB failed to open file:/var/lib/taos/mgmt/user.db
ERROR MND failed to init user data
ERROR MND failed to init users
ERROR DND TDengine mgmt initialization failed

**Comment by EricWice** [comment]
我也遇到过，后来只能通过把/var/lib/taos和/usr/local/taos下面的文件清除干净再重装之后解决

**Comment by tssunjingwu** [comment]
解决了，手动创建的/var/lib/taos

**Comment by tssunjingwu** [comment]
> 我也遇到过，后来只能通过把/var/lib/taos和/usr/local/taos下面的文件清除干净再重装之后解决

jdbc 接连失败遇到过吗，shell 通过taos可以连接，通过官方提供的Java Connector例子连接失败

**Comment by EricWice** [comment]
> Java Connector

没遇到过类似问题，但我用的Python，没用过Java Connector。

**Comment by tssunjingwu** [comment]
> > Java Connector
> 
> 没遇到过类似问题，但我用的Python，没用过Java Connector。

解决了，Java Connector必须用127.0.0.1，但我通过taos是指定的是局域网ip

**Comment by tssunjingwu** [comment]
> > > Java Connector
> > 
> > 
> > 没遇到过类似问题，但我用的Python，没用过Java Connector。
> 
> 解决了，Java Connector必须用127.0.0.1，但我通过taos是指定的是局域网ip

可以了，有点诡异

**Comment by Solskjaer20** [comment]
查询有10亿条记录的表，提示：TSDB error: failed to connect to server，
查看服务状态：
● taosd.service - TDengine server service
   Loaded: loaded (/etc/systemd/system/taosd.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2019-07-16 14:43:56 CST; 3 weeks 1 days ago
 Main PID: 14186 (taosd)
    Tasks: 28
   CGroup: /system.slice/taosd.service
           └─14186 /usr/bin/taosd
Jul 16 14:43:56 cdh1 systemd[1]: Started TDengine server service.
Jul 16 14:43:56 cdh1 systemd[1]: Starting TDengine server service...
Jul 16 14:43:56 cdh1 TDengine:[14186]: Starting TDengine service...
Jul 16 14:43:56 cdh1 TDengine:[14186]: Started TDengine service successfully.

没有看到异常，于是隔了1分钟左右，再次查询，查询返回结果，正确。
实在不清楚是啥问题才导致提示连接不上服务，然后又莫名其妙的恢复正常，
哪位前辈指点下，谢谢
