### ISSUE TITLE
couldn't find /var/lib/taos//dnode/dnode.json、/var/lib/taos//mnode/mnode.json

### ISSUE THREAD

**Issue by helloworldwyy** [taosdata/TDengine#20337]
03/08 15:57:43.912701 00003887 DND start to init dnode env
03/08 15:57:43.912854 00003887 DND succceed to read dnode file /var/lib/taos//dnode/dnode.json
03/08 15:57:43.912934 00003887 DND succceed to read mnode file /var/lib/taos//mnode/mnode.json
03/08 15:57:43.912943 00003887 DND file:/var/lib/taos//qnode/qnode.json not exist
03/08 15:57:43.912946 00003887 DND file:/var/lib/taos//snode/snode.json not exist
03/08 15:57:44.916215 00003887 DND ERROR failed to lock file:/var/lib/taos//.running since Resource temporarily unavailable, retryTimes:1
03/08 15:57:45.916300 00003887 DND ERROR failed to lock file:/var/lib/taos//.running since Resource temporarily unavailable, retryTimes:2

**Comment by helloworldwyy** [comment]
启动能正常用，systemctl status taosd 状态还是正常的，但是无法连接(taos和客户端都连不上)

**Comment by yu285** [comment]
版本号是？ 可以加 a15652223354 远程看下

**Comment by MeiZhiLi** [comment]
taosd 看日志同样报错、好奇这是什么错误了？
不影响使用、创建表、添加数据、查询数据正常使用
05/26 11:14:33.633267 00020743 UTL default      os sysname               Linux
05/26 11:14:33.633271 00020743 UTL default      os nodename              swan002
05/26 11:14:33.633275 00020743 UTL default      os release               3.10.0-327.el7.x86_64
05/26 11:14:33.633278 00020743 UTL default      os version               #1 SMP Thu Nov 19 22:10:57 UTC 2015
05/26 11:14:33.633282 00020743 UTL default      os machine               x86_64
05/26 11:14:33.633286 00020743 UTL default      version                  3.0.4.1
05/26 11:14:33.633362 00020743 UTL default      compatible_version       3.0.0.0
05/26 11:14:33.633370 00020743 UTL default      gitinfo                  14dc9eabc403e731ba1097eca0bcaa902c6d5b62
05/26 11:14:33.633375 00020743 UTL default      buildinfo                Built at 2023-04-27 11:08
05/26 11:14:33.633379 00020743 UTL =================================================================
05/26 11:14:33.635898 00020743 DND start to init dnode env
05/26 11:14:33.636000 00020743 DND succceed to read dnode file /var/lib/taos//dnode/dnode.json
05/26 11:14:33.636365 00020743 DND succceed to read mnode file /var/lib/taos//mnode/mnode.json
05/26 11:14:33.636379 00020743 DND file:/var/lib/taos//qnode/qnode.json not exist
05/26 11:14:33.636386 00020743 DND file:/var/lib/taos//snode/snode.json not exist
05/26 11:14:34.636673 00020743 DND ERROR failed to lock file:/var/lib/taos//.running since Resource temporarily unavailable, retryTimes:1
05/26 11:14:35.636773 00020743 DND ERROR failed to lock file:/var/lib/taos//.running since Resource temporarily unavailable, retryTimes:2
05/26 11:14:36.636878 00020743 DND ERROR failed to lock file:/var/lib/taos//.running since Resource temporarily unavailable, retryTimes:3
05/26 11:14:37.637003 00020743 DND ERROR failed to lock file:/var/lib/taos//.running since Resource temporarily unavailable, retryTimes:4
05/26 11:14:38.637120 00020743 DND ERROR failed to lock file:/var/lib/taos//.running since Resource temporarily unavailable, retryTimes:5
05/26 11:14:39.637250 00020743 DND ERROR failed to lock file:/var/lib/taos//.running since Resource temporarily unavailable, retryTimes:6
05/26 11:14:40.637375 00020743 DND ERROR failed to lock file:/var/lib/taos//.running since Resource temporarily unavailable, retryTimes:7
05/26 11:14:41.637482 00020743 DND ERROR failed to lock file:/var/lib/taos//.running since Resource temporarily unavailable, retryTimes:8
05/26 11:14:42.637597 00020743 DND ERROR failed to lock file:/var/lib/taos//.running since Resource temporarily unavailable, retryTimes:9
05/26 11:14:43.637709 00020743 DND ERROR failed to lock file:/var/lib/taos//.running since Resource temporarily unavailable, retryTimes:10
05/26 11:14:44.637812 00020743 DND ERROR failed to lock file:/var/lib/taos//.running since Resource temporarily unavailable, retryTimes:11
05/26 11:14:45.637926 00020743 DND ERROR failed to lock file:/var/lib/taos//.running since Resource temporarily unavailable, retryTimes:12
05/26 11:14:45.637964 00020743 DND ERROR failed to create dnode since Resource temporarily unavailable
05/26 11:14:45.638327 00020743 DND ERROR failed to init dnode since Resource temporarily unavailable

**Comment by yu285** [comment]
这是重复启动

**Comment by TomatoYoung** [comment]
我也是这个报错，所以应该怎么解决？
