### ISSUE TITLE
DB error: udf pipe read error

### ISSUE THREAD

**Issue by hb0902** [taosdata/TDengine#20701]
版本3.0.2.4实现自定义函数，返回nchar时报错
![image](https://user-images.githubusercontent.com/20200057/228706109-b6b5ca23-3c05-4bbe-a3f6-7ce546067f6c.png)

自定义函数代码：

#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <math.h>

#include "taosudf.h"

// 初始化
DLL_EXPORT int32_t block_max_col_agg_init()
{
  return 0;
}

// 销毁
DLL_EXPORT int32_t block_max_col_agg_destroy()
{
  return 0;
}

// aggregate start function. The intermediate value or the state(@interBuf) is initialized in this function. The function name shall be concatenation of udf name and _start suffix
// @param interbuf intermediate value to intialize
// @return error number defined in taoserror.h
DLL_EXPORT int32_t block_max_col_agg_start(SUdfInterBuf *buf)
{
  *(int64_t *)(buf->buf) = 0;
  buf->bufLen = sizeof(double);
  buf->numOfResult = 0;
  return 0;
}

// interBuf：中间结果 buffer。
// inputBlock：输入的数据块。
// newInterBuf：新的中间结果buffer。
// result：最终结果。
DLL_EXPORT int32_t block_max_col_agg(SUdfDataBlock *block, SUdfInterBuf *interBuf, SUdfInterBuf *newInterBuf)
{
  float maxValue = *(double *)interBuf->buf;
  char *maxValueCol = "";
  maxValue = -999999999.99;
  int8_t numNotNull = 0;
  // 校验列数必须为2
  if (block->numOfCols < 2)
  {
    return TSDB_CODE_UDF_INVALID_INPUT;
  }
  // 校验数据类型
  for (int32_t i = 0; i < block->numOfCols; ++i)
  {
    SUdfColumn *col = block->udfCols[i];
    if (!(col->colMeta.type == TSDB_DATA_TYPE_FLOAT || col->colMeta.type == TSDB_DATA_TYPE_NCHAR))
    {
      return TSDB_CODE_UDF_INVALID_INPUT;
    }
  }
  // 循环计算统计结果

  SUdfColumn *lastCol = block->udfCols[block->numOfCols];
  for (int32_t i = 0; i < (block->numOfCols - 1); ++i)
  {
    for (int32_t j = 0; j < block->numOfRows; ++j)
    {
      SUdfColumn *col = block->udfCols[i];
      if (udfColDataIsNull(col, j))
      {
        continue;
      }
      char *cell = udfColDataGetData(col, j);
      float num = *(float *)cell;
      if (num > maxValue)
      {
        maxValue = num;
        sprintf(maxValueCol, "%s%s%d", udfColDataGetData(lastCol, j), "_", i);
      }
      ++numNotNull;
    }
  }

  newInterBuf->buf = maxValueCol;
  newInterBuf->bufLen = strlen(maxValueCol);
  newInterBuf->numOfResult = 1;
  return 0;
}

DLL_EXPORT int32_t block_max_col_agg_finish(SUdfInterBuf *buf, SUdfInterBuf *resultData)
{
  resultData->buf = buf->buf;
  resultData->bufLen = strlen(buf->buf);
  resultData->numOfResult = 1;
  return 0;
}

**Comment by shenglian-zhou** [comment]
thanks a lot for your interest in UDF.
It is a known issue. 
could you please try the udf with 3.0 latest version and build from source? thanks a lot.

**Comment by yu285** [comment]
any update after using 3.0.3.1 ?

**Comment by DuanKuanJun** [comment]
@hb0902 , would you share  me Vol1,Vol2,Vol3 and mRID datatype, I guest that datatype is float,float,float and NCHAR , is ok?

**Comment by DuanKuanJun** [comment]
@hb0902 , your code have some error, I fixed.
In addition, I advise that you can store string in varchar datatype instead NCHAR datatype.
Because varchar is simple, store with ansi ,  need not to covert codepage. NCHAR store with unicode codepage, need to deal codepage.

bellow is test result:

---- create command ------
create aggregate function block_max_col_agg as '/root/udf/user1/libuser1.so' outputtype binary(64) bufsize 10240 language 'C';
----- table describle -------

taos> describe batterybox_meas;
             field              |         type         |   length    |   note   |
=================================================================================
 ts                             | TIMESTAMP            |           8 |          |
 vol1                           | FLOAT                |           4 |          |
 vol2                           | FLOAT                |           4 |          |
 vol3                           | FLOAT                |           4 |          |
 rid                            | VARCHAR              |          32 |          |
Query OK, 5 row(s) in set (0.001576s)

taos> select block_max_col_agg(vol1,vol2,vol3,mrid) from batterybox_meas;
 block_max_col_agg(vol1,vol2,vol3,mrid) |
=========================================
 ridnew_1_2005.000000                   |
Query OK, 1 row(s) in set (0.006957s)

taos> select * from batterybox_meas;
           ts            |         vol1         |         vol2         |         vol3         |              mrid              |
================================================================================================================================
 2023-04-07 12:54:30.974 |         1.000000e+00f |         2.000000e+00f |         3.000000e+00f | rid1                           |
 2023-04-07 12:54:46.669 |         1.000000e+01f |         2.000000e+01f |         3.000000e+01f | rid10                          |
 2023-04-07 12:54:59.085 |         1.000000e+02f |         2.000000e+02f |         3.000000e+02f | rid100                         |
 2023-04-07 13:40:06.179 |         5.000000e+00f |         6.000000e+00f |         7.000000e+00f | ridnew                         |
 2023-04-07 13:41:12.694 |         1.000000e+03f |         2.000000e+03f |         2.001000e+03f | ridnew                         |
 2023-04-07 13:41:34.637 |         1.000000e+03f |         2.005000e+03f |         2.001000e+03f | ridnew                         |
Query OK, 6 row(s) in set (0.003324s)


//
// udf.c source code
//

#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <math.h>

#include "taosudf.h"

#define STR_MAX_LEN 256 // inter buffer length

// init
DLL_EXPORT int32_t block_max_col_agg_init()
{
    return 0;
}

// destory
DLL_EXPORT int32_t block_max_col_agg_destroy()
{
    return 0;
}

// aggregate start function. The intermediate value or the state(@interBuf) is initialized in this function. The function name shall be concatenation of udf name and _start suffix
// @param interbuf intermediate value to intialize
// @return error number defined in taoserror.h
DLL_EXPORT int32_t block_max_col_agg_start(SUdfInterBuf *buf)
{
    memset(buf->buf, 0, sizeof(float) + STR_MAX_LEN);
    buf->bufLen = sizeof(float)  + STR_MAX_LEN;
    buf->numOfResult = 0;
    return 0;
}

// interBuf：中间结果 buffer。
// inputBlock：输入的数据块。
// newInterBuf：新的中间结果buffer。
// result：最终结果。
DLL_EXPORT int32_t block_max_col_agg(SUdfDataBlock *block, SUdfInterBuf *interBuf, SUdfInterBuf *newInterBuf)
{
    //return 0;
    float maxValue = *(float *)interBuf->buf;
    char maxValueCol[STR_MAX_LEN] = "";
    maxValue = -999999999.99;
    int8_t numNotNull = 0;
    // 校验列数必须为2
    if (block->numOfCols < 2)
    {
        return TSDB_CODE_UDF_INVALID_INPUT;
    }
    // 校验数据类型
    for (int32_t i = 0; i < block->numOfCols; ++i)
    {
        SUdfColumn *col = block->udfCols[i];
        if (!(col->colMeta.type == TSDB_DATA_TYPE_FLOAT || col->colMeta.type == TSDB_DATA_TYPE_BINARY))
        {
            return TSDB_CODE_UDF_INVALID_INPUT;
        }
    }
    // 循环计算统计结果

    SUdfColumn *lastCol = block->udfCols[block->numOfCols-1];
    for (int32_t i = 0; i < (block->numOfCols - 1); ++i)
    {
        for (int32_t j = 0; j < block->numOfRows; ++j)
        {
            SUdfColumn *col = block->udfCols[i];
            if (udfColDataIsNull(col, j))
            {
                continue;
            }
            char *cell = udfColDataGetData(col, j);
            float num = *(float *)cell;
            if (num > maxValue)
            {
                maxValue = num;
		        char *valData = udfColDataGetData(lastCol, j);
                char *val = valData + sizeof(short);
                sprintf(maxValueCol, "%s_%d_%f", val, i, maxValue);
            }
            ++numNotNull;
        }
    }

    *(float*)newInterBuf->buf = maxValue;
    strcpy(newInterBuf->buf + sizeof(float), maxValueCol);
    newInterBuf->bufLen = sizeof(float) + strlen(maxValueCol)+1;
    newInterBuf->numOfResult = 1;
    return 0;
}

DLL_EXPORT int32_t block_max_col_agg_finish(SUdfInterBuf *buf, SUdfInterBuf *resultData)
{
    char * str = buf->buf + sizeof(float);
    // copy to des
    char * des = resultData->buf + sizeof(short);
    strcpy(des, str);

    // set binary type len
    short  len = strlen(str);
    *((short*)resultData->buf) = len;

    // set buf len
    resultData->bufLen = len + sizeof(short);
    // set row count
    resultData->numOfResult = 1;
    return 0;
}

**Comment by gccgdb1234** [comment]
@hb0902  此问题使用修改后的 UDF 代码是否已经解决？
