### ISSUE TITLE
DBeaver USE database

### ISSUE THREAD

**Issue by Bit0r** [taosdata/TDengine#21951]
When I execute `USE [database]` in dbeaver, such as `use power;`, the following error will occur:
```
SQL 错误: jdbc 驱动内部错误
  jdbc 驱动内部错误
  jdbc 驱动内部错误
    Illegal character in path at index 34: http://localhost:6041/rest/sql/use power
    Illegal character in path at index 34: http://localhost:6041/rest/sql/use power
```
IIt seems that the HTTP URL contains spaces?
![image](https://github.com/taosdata/TDengine/assets/43108543/c1637810-5322-4e43-8730-7baea8a00fda)

**Comment by arthur19q3** [comment]
it seems when you execute "USE [database];" with DBeaver, specifically "USE power;", it results in an error message indicating that there's an illegal character in the path. The error message suggests that the issue lies with the URL path used to connect to the database via JDBC.

To resolve this issue, maybe you should not include the "USE" statement in the SQL editor of DBeaver. Instead, you might as well select the desired database from the database navigator panel or the connection properties, and DBeaver will automatically establish the connection to that particular database.

**Comment by Bit0r** [comment]
The driver of this database does not support the "set as default database" operation.

**Comment by arthur19q3** [comment]
well then give the fuck up.

**Comment by yu285** [comment]
https://docs.taosdata.com/third-party/dbeaver/
