### ISSUE TITLE
failed to open log file:/opt/taos/log/taoslog0.0, reason:No such file or directory

### ISSUE THREAD

**Issue by nonamexz** [taosdata/TDengine#223]
版本：1.6.1.1 rpm版
操作系统：CentOS7.6
安装后，修改了taos.conf的数据库和日志目录位置：
![image](https://user-images.githubusercontent.com/13826400/62035419-59660080-b222-11e9-994c-95c291a1a044.png)
启动数据库后，执行taos报如下错误：
![image](https://user-images.githubusercontent.com/13826400/62035455-77336580-b222-11e9-8c02-c9bdfc13baeb.png)

**Comment by plum-lihui** [comment]
taosd服务启动了吗？请使用命令 ps -ef | grep taosd 确认一下。

**Comment by nonamexz** [comment]
现在现场已经被破坏了，可以确定的是，我修改完配置后执行过systemctl start taosd.
后来我手工创建了/opt/taos/log目录后，再次执行了systemctl start taosd.  登陆正常。

**Comment by plum-lihui** [comment]
好的，请继续试用测试吧。有问题请提交到这里，我们会跟踪解决的。多谢！

**Comment by delores534** [comment]
macOS 从13升级到15后，TDengine 通过 jdbc 连接后出现 Error querying database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: JNI ERROR (0x2354): Operation not permitted 的异常；在命令行输入taos 也是出现异常 failed to create dir:/var/log/taos/ since Operation not permitted WARING: Create taoslog failed:Operation not permitted. configDir=/etc/taos/；只有输入 sudo taos 才能正常进入
