### ISSUE TITLE
ODBC数据源添加报错126

### ISSUE THREAD

**Issue by cttq-iot** [taosdata/TDengine#28510]
**Bug Description**
版本：3.3.3.0 下载windows client 到本地安装；添加ODBC-64位数据源，报错
![image](https://github.com/user-attachments/assets/3202afe4-907a-4c96-9a10-b7b0394cbc69)

**Comment by YamingPei** [comment]
[MS VC++ 2015+ dll.zip](https://github.com/user-attachments/files/17520010/MS.VC%2B%2B.2015%2B.dll.zip)
It seems that the error is caused by the missing vc++ dependent library, please extract the compressed package in the attachment, copy the file to: C:\Windows\System32\ and C:\Windows\Syswow64\ directory
