### ISSUE TITLE
Grafana plugin cannot be found in the local directory

### ISSUE THREAD

**Issue by iwasjoker** [taosdata/TDengine#3315]
I want show data by grafana ,but I can't find plugin in local path :/usr/local/taos/connector/grafanaplugin.
I use TDengine-server-2.0.2.1-Linux-x64.rpm installed TDengine.
How can I solve this problem.
                                                                                                                                                                   Looking forward to your help!

**Comment by plum-lihui** [comment]
sorry! This is really missing. Because we made grafanaplugin into a sub module, we didn't clone it properly when we packed it.
The next version will be corrected. If you are in a hurry, you can download it yourself and put it in this directory.
download url：https://github.com/taosdata/grafanaplugin/tree/d598db167eb256fe67409b7bb3d0eb7fffc3ff8c

Thanks！

**Comment by iwasjoker** [comment]
> sorry! This is really missing. Because we made grafanaplugin into a sub module, we didn't clone it properly when we packed it.
> The next version will be corrected. If you are in a hurry, you can download it yourself and put it in this directory.
> download url：https://github.com/taosdata/grafanaplugin/tree/d598db167eb256fe67409b7bb3d0eb7fffc3ff8c
> 
> Thanks！

OK，Thanks!
