### ISSUE TITLE
timer issues

### ISSUE THREAD

**Issue by localvar** [taosdata/TDengine#368]
I will use this issue to track all issues I found in timer implementation and will make an update if I found new ones and will try to help fixing them. please feel free to correct me if I made mistakes and I will update accordingly also.

1. #367 

2. resource leak: if `param1` of `taosTmrStart` is dynamic allocated resource, and `taosTmrStopA` or `taosTmrReset` is called later, the resource may leak. this also happens when a timer controller is destroyed.

3. no need to keep timers sorted by `cycle` as `taosTmrProcessList` always iterates the whole list.

4. https://github.com/taosdata/TDengine/blob/542da25452bc529e6802f9c41636f5c6a3f92ef9/src/util/src/ttimer.c#L280-L287
should not pass `header` to the scheduled timer call back as it is freed immediately after the callback is scheduled. 

5. `memset` should be done after `if`
https://github.com/taosdata/TDengine/blob/542da25452bc529e6802f9c41636f5c6a3f92ef9/src/util/src/ttimer.c#L540-L544

6. memory leak, `memset` should be removed. https://github.com/taosdata/TDengine/blob/542da25452bc529e6802f9c41636f5c6a3f92ef9/src/util/src/ttimer.c#L593-L601

**Comment by jtao1735** [comment]
Thanks for taking time to review the code. 
1: #367,  not a problem right now
2: param1 is passed into timer by app, the deallocation shall be controlled by app. 
3: it is true, but we need to re-write line 262-269  
4: header here actually is the timerId, it can be used by app to do some checking, even it is freed
5: memset it not needed here, since freeList is initialized at line 552
6: memset here is a good practice
