### ISSUE TITLE
docker运行springboot项目，执行方法提示：Could not initialize class com.taosdata.jdbc.TSDBJNIConnector

### ISSUE THREAD

**Issue by 419845351** [taosdata/TDengine#4274]
**General Questions**
在docker容器中运行springboot项目。
项目启动后，调用方法时先提示：java.lang.UnsatisfiedLinkError: no taos in java.library.path
再次调用方法提示：java.lang.NoClassDefFoundError: Could not initialize class com.taosdata.jdbc.TSDBJNIConnector
我把TDengine-client-2.0.6.0-Linux-x64.tar.gz包映射到容器中，解压，安装。提示：install_client.sh: 65: Syntax error: "(" unexpected。
请问容器中怎么安装客户端？还要什么环境么？

**Comment by 419845351** [comment]
命令写错了，问题解决。

**Comment by kct12345** [comment]
Dockerfile文件可以参考下吗
我就是使用docker运行不起来谢谢
FROM openjdk:8-jdk-alpine

VOLUME /tmp

EXPOSE 8081

ADD ./taos-jb-service.jar /app.jar
ADD ./libtaos.so.2.0.20.17 /usr/lib
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
ENV JAVA_OPTS=""

ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /app.jar" ]

**Comment by kct12345** [comment]
问题解决就行，可以写解决方案在issuse里面，彼此参考。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "taosdata/TDengine"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月15日(星期五) 下午5:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [taosdata/TDengine] docker运行springboot项目，执行方法提示：Could not initialize class com.taosdata.jdbc.TSDBJNIConnector (#4274)





 不好意思，刚看到。 
 我现在用的是笨办法，把TDengine-client在启动命令里映射进来，在容器里启动client。 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "taosdata/TDengine"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年10月14日(星期四) 上午10:52 
 ***@***.***&amp;gt;; 
 ***@***.***&amp;gt;;"State ***@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [taosdata/TDengine] docker运行springboot项目，执行方法提示：Could not initialize class com.taosdata.jdbc.TSDBJNIConnector (#4274) 
 
 
 
 
 
   
 Dockerfile文件可以参考下吗 
  我就是使用docker运行不起来谢谢 
  FROM openjdk:8-jdk-alpine 
   
 VOLUME /tmp 
   
 EXPOSE 8081 
   
 ADD ./taos-jb-service.jar /app.jar 
  ADD ./libtaos.so.2.0.20.17 /usr/lib 
  ENV TZ=Asia/Shanghai 
  RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime &amp;amp;&amp;amp; echo $TZ &amp;gt; /etc/timezone 
  ENV JAVA_OPTS="" 
   
 ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /app.jar" ] 
   
 — 
 You are receiving this because you modified the open/close state. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
