### ISSUE TITLE
IDEA connect to TDengine failed

### ISSUE THREAD

**Issue by POPIWEN0209** [taosdata/TDengine#6602]
数据库出不来还报错
![image](https://user-images.githubusercontent.com/71167273/123188507-b9c55180-d4ce-11eb-9f9e-fc4f513c23f8.png)
![image](https://user-images.githubusercontent.com/71167273/123188538-c77ad700-d4ce-11eb-94c6-f77a56862d0d.png)
![image](https://user-images.githubusercontent.com/71167273/123188592-df525b00-d4ce-11eb-83ef-87de888b4619.png)
错误信息：<failed to load>
java.sql.SQLException: ERROR (2315): unknown taos type in tdengine
	at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:70)
	at com.taosdata.jdbc.TSDBError.createSQLException(TSDBError.java:57)
	at com.taosdata.jdbc.TSDBConstants.taosType2JdbcType(TSDBConstants.java:128)
	at com.taosdata.jdbc.TSDBResultSetMetaData.getColumnType(TSDBResultSetMetaData.java:154)
	in RemoteResultSetMetaDataImpl.getFixedColumnType(RemoteResultSetMetaDataImpl.java:105)

**Comment by yu285** [comment]
jdbc 2.0.31要和数据库2.1.3配合使用，请问您数据库什么版本

**Comment by POPIWEN0209** [comment]
> jdbc 2.0.31 要和数据库2.1.3 配合使用，请告知您数据库什么版本

2.1.2.0

**Comment by yu285** [comment]
> > jdbc 2.0.31 要和数据库2.1.3 配合使用，请告知您数据库什么版本
> 
> 2.1.2.0

那请更换一下，再看看

**Comment by jjhgxk** [comment]
我这边就是数据库2.1.3 jdbc是2.0.31的jar包 但是还是提示这样的错误

**Comment by xleili** [comment]
这个问题如果用2.0.31的jdbc包，确实会报unknown taos type in tdengine。但是他还是可以进行sql查询。

**Comment by xleili** [comment]
> 这个问题如果用2.0.31的jdbc包，确实会报unknown taos type in tdengine。但是他还是可以进行sql查询。

￼你可以考虑到https://www.taosdata.com/cn/all-downloads/ 中下载TDengine-client-2.0.20.0-Linux-x64.tar，解压然后在connector文件夹下找到taos-jdbcdriver-2.0.27-dist.jar。用个jar替换原来的jar包，这样的话会显示数据库实例
![image](https://user-images.githubusercontent.com/85657333/124083430-6d56b480-da80-11eb-9836-d7f0a8ec968b.png)
![image](https://user-images.githubusercontent.com/85657333/124083497-81021b00-da80-11eb-8a30-8ca8f9b1cffa.png)

**Comment by jjhgxk** [comment]
我按照这个去改了 我去这个网址下载去搜索这个TDengine-client-2.0.20.0-Linux-x64.tar,截图如下 下载的是这个tar包 不知道是否下载链接是否有误 然后下载下来去找jar包 我的是2.0.28的,我尝试了一下 还是不行 就提示这个了









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "taosdata/TDengine"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月1日(星期四) 下午3:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [taosdata/TDengine] IDEA connect to TDengine failed (#6602)





  
这个问题如果用2.0.31的jdbc包，确实会报unknown taos type in tdengine。但是他还是可以进行sql查询。
  
￼你可以考虑到https://www.taosdata.com/cn/all-downloads/ 中下载TDengine-client-2.0.20.0-Linux-x64.tar，解压然后在connector文件夹下找到taos-jdbcdriver-2.0.27-dist.jar。用个jar替换原来的jar包，这样的话会显示数据库实例

**Comment by xleili** [comment]
> 我按照这个去改了 我去这个网址下载去搜索这个TDengine-client-2.0.20.0-Linux-x64.tar,截图如下 下载的是这个tar包 不知道是否下载链接是否有误 然后下载下来去找jar包 我的是2.0.28的,我尝试了一下 还是不行 就提示这个了
> […](#)

能看看看的jar包，我也是从给你的链接下载。你看看你的是不是jdbc包带不带dist
![image](https://user-images.githubusercontent.com/85657333/124093368-62088680-da8a-11eb-8eab-a4b2d24dc597.png)

**Comment by xleili** [comment]
> 我按照这个去改了 我去这个网址下载去搜索这个TDengine-client-2.0.20.0-Linux-x64.tar,截图如下 下载的是这个tar包 不知道是否下载链接是否有误 然后下载下来去找jar包 我的是2.0.28的,我尝试了一下 还是不行 就提示这个了
> […](#)

还是不行。指的是不能执行sql，还是数据实例看不到？

**Comment by jjhgxk** [comment]
不行是指我现在点击test都不行了了 提示错误setTimstamp 我的jdbc我是按照上面的目前带了dist  可是连连接都报错了

**Comment by jjhgxk** [comment]
我试了27,28都不行,连接都报错,见下图





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "taosdata/TDengine"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月1日(星期四) 下午4:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [taosdata/TDengine] IDEA connect to TDengine failed (#6602)





  
我按照这个去改了 我去这个网址下载去搜索这个TDengine-client-2.0.20.0-Linux-x64.tar,截图如下 下载的是这个tar包 不知道是否下载链接是否有误 然后下载下来去找jar包 我的是2.0.28的,我尝试了一下 还是不行 就提示这个了
 …
  
还是不行。指的是不能执行sql，还是数据实例看不到？

**Comment by xleili** [comment]
> 不行是指我现在点击test都不行了了 提示错误setTimstamp 我的jdbc我是按照上面的目前带了dist 可是连连接都报错了
能看下你的配置吗？

**Comment by jjhgxk** [comment]
是指哪块的配置&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "taosdata/TDengine"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月1日(星期四) 下午4:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [taosdata/TDengine] IDEA connect to TDengine failed (#6602)





  
不行是指我现在点击test都不行了了 提示错误setTimstamp 我的jdbc我是按照上面的目前带了dist 可是连连接都报错了
 能看下你的配置吗？

**Comment by xleili** [comment]
> 是指哪块的配置&nbsp;
> […](#)
添加datasource的配置 和添加driver的配置
![image](https://user-images.githubusercontent.com/85657333/124099692-5fa92b00-da90-11eb-9cb3-907648bcc8ed.png)

![Uploading image.png…]()

**Comment by jjhgxk** [comment]
已经发您了
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "taosdata/TDengine"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月1日(星期四) 下午5:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [taosdata/TDengine] IDEA connect to TDengine failed (#6602)





  
是指哪块的配置&nbsp;
 …
 添加datasource的配置 和添加driver的配置

**Comment by xleili** [comment]
> 已经发您了 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "taosdata/TDengine" ***@***.***&gt;; 发送时间:&nbsp;2021年7月1日(星期四) 下午5:18 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [taosdata/TDengine] IDEA connect to TDengine failed (#6602) 是指哪块的配置&nbsp; … 添加datasource的配置 和添加driver的配置 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

看下您dist 包的配置，非dist包配置了目前就是这样会报错，看不到数据库实例，但是能查询。https://github.com/taosdata/TDengine/issues/6602#issuecomment-871992263

**Comment by jjhgxk** [comment]
不是非常的明白，您这边是指window端的客户端的配置文件吗&nbsp;我目前linux服务端和window客户端 能具体截图说明吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "taosdata/TDengine"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月1日(星期四) 下午5:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [taosdata/TDengine] IDEA connect to TDengine failed (#6602)





  
已经发您了 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "taosdata/TDengine" @.&gt;; 发送时间:&nbsp;2021年7月1日(星期四) 下午5:18 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [taosdata/TDengine] IDEA connect to TDengine failed (#6602) 是指哪块的配置&nbsp; … 添加datasource的配置 和添加driver的配置 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
看下您dist 包的配置，非dist包配置了目前就是这样会报错，看不到数据库实例，但是能查询。#6602 (comment)

**Comment by POPIWEN0209** [comment]
> 不是非常清楚，您是指window端的客户端的配置文件吗 我现在的linux服务端和window客户端能具体截图说明吗
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "taosdata/TDengine" ***@***.***&gt;; 发送时间:&nbsp;2021年7月1日(星期四) 下午5:42 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [taosdata/TDengine] IDEA connect to TDengine failed (#6602) 已经发您了 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "taosdata/TDengine" @.&gt;; 发送时间:&nbsp;2021年7月1日(星期四) 下午5:18 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [taosdata/TDengine] IDEA connect to TDengine failed (#6602) 是指哪块的配置&nbsp; … 添加datasource的配置 和添加driver的配置 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 看下您dist 包的配置，非dist包配置了目前就是这样会报错，看不到数据库实例，但是能查询。#6602 (comment) — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

其实除了这个，tdengine还有自己开发的可视化工具

**Comment by jjhgxk** [comment]
可否发一下 我想试用一下可视化工具

**Comment by yu285** [comment]
https://www.taosdata.com/blog/2021/03/03/2202.html

**Comment by yu285** [comment]
> 可否发一下 我想试用一下可视化工具

https://www.taosdata.com/blog/2021/03/03/2202.html

**Comment by xleili** [comment]
> 不是非常的明白，您这边是指window端的客户端的配置文件吗&nbsp;我目前linux服务端和window客户端 能具体截图说明吗
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "taosdata/TDengine" ***@***.***&gt;; 发送时间:&nbsp;2021年7月1日(星期四) 下午5:42 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [taosdata/TDengine] IDEA connect to TDengine failed (#6602) 已经发您了 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "taosdata/TDengine" @.&gt;; 发送时间:&nbsp;2021年7月1日(星期四) 下午5:18 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [taosdata/TDengine] IDEA connect to TDengine failed (#6602) 是指哪块的配置&nbsp; … 添加datasource的配置 和添加driver的配置 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 看下您dist 包的配置，非dist包配置了目前就是这样会报错，看不到数据库实例，但是能查询。#6602 (comment) — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.


方便远程帮您看一下吗？我的邮箱xlli@taosdata.com

**Comment by xleili** [comment]
> > 不是非常的明白，您这边是指window端的客户端的配置文件吗 我目前linux服务端和window客户端 能具体截图说明吗
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "taosdata/TDengine" _**@**_._**>; 发送时间: 2021年7月1日(星期四) 下午5:42 _**@**_.**_>; _**@**_._**_**@**_.**_>; 主题: Re: [taosdata/TDengine] IDEA connect to TDengine failed (#6602) 已经发您了 ------------------ 原始邮件 ------------------ 发件人: "taosdata/TDengine" @.>; 发送时间: 2021年7月1日(星期四) 下午5:18 @.>; @.@.>; 主题: Re: [taosdata/TDengine] IDEA connect to TDengine failed (#6602) 是指哪块的配置  … 添加datasource的配置 和添加driver的配置 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 看下您dist 包的配置，非dist包配置了目前就是这样会报错，看不到数据库实例，但是能查询。#6602 (comment) — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 方便远程帮您看一下吗？我的邮箱[xlli@taosdata.com](mailto:xlli@taosdata.com)

有向日葵吗

**Comment by jjhgxk** [comment]
我用了你们的可视化工具了 可以使用 我就暂时先不用idea了吧 还有公司电脑操纵不了 会被监控 谢了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "taosdata/TDengine"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月2日(星期五) 上午10:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [taosdata/TDengine] IDEA connect to TDengine failed (#6602)





   
不是非常的明白，您这边是指window端的客户端的配置文件吗&nbsp;我目前linux服务端和window客户端 能具体截图说明吗
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "taosdata/TDengine" @.&gt;; 发送时间:&nbsp;2021年7月1日(星期四) 下午5:42 _@**._&gt;; ***@***.***@.**_&gt;; 主题:&nbsp;Re: [taosdata/TDengine] IDEA connect to TDengine failed (#6602) 已经发您了 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "taosdata/TDengine" @.&gt;; 发送时间:&nbsp;2021年7月1日(星期四) 下午5:18 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [taosdata/TDengine] IDEA connect to TDengine failed (#6602) 是指哪块的配置&nbsp; … 添加datasource的配置 和添加driver的配置 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 看下您dist 包的配置，非dist包配置了目前就是这样会报错，看不到数据库实例，但是能查询。#6602 (comment) — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
***@***.***
  
有向日葵吗
