### ISSUE TITLE
./taosdemo  run failed

### ISSUE THREAD

**Issue by paopaol** [taosdata/TDengine#736]
when i'm run 
```shell
 ./taosdemo -t 1 -n 2
```
the output is

```log
11/17 10:32:16.198007 76f7b000 ERROR UTL open file:/proc/1085/io failed
Creating meters super table...
meters created!
Creating 1 table(s)......
Table(s) created!
Inserting data......
Failed to run insert into test.t0 values (1056413696, 5, 0, 8) (1056413697, 6, 8, 9), reason: timestamp out of range
```
the reason it said:timestamp out of range, why?
how could i do?

**Comment by fangpanpan** [comment]
1. the timestamp value is a long integer representing milliseconds since the epoch. (The number of digits of your timestamp value is 10. For milliseconds, it is a number with 13 digits.
2. our default retention for the database is 10 years. So the earliest time you can insert into the database is 2018-11-19 00:00:000) 
3. the default start time in the taosdemo is 1500000000000; Have you changed it?

**Comment by paopaol** [comment]
@fangpanpan  Not yet, how can I modify it?

**Comment by paopaol** [comment]
![QQ截图20191118162335](https://user-images.githubusercontent.com/6983082/69035970-d3173980-0a1f-11ea-88ca-65226d61c5d3.jpg)
i change  the start time now,but still failed

**Comment by fangpanpan** [comment]
> ![QQ截图20191118162335](https://user-images.githubusercontent.com/6983082/69035970-d3173980-0a1f-11ea-88ca-65226d61c5d3.jpg)
> i change the start time now,but still failed

"time(NULL)" returns the number in seconds(10digits), but our timestamp is in milliseconds (13digits). Could you just change the "time(NULL)" to 1500000000000 or multiply it by 1000 and try it again?

**Comment by paopaol** [comment]
@fangpanpan  I have tried it and it is a failure.

**Comment by fangpanpan** [comment]
> @fangpanpan I have tried it and it is a failure.
could you show me the screenshot of the failure? It will print out the SQL command so I can see your timestamp.
