### ISSUE TITLE
autogen.sh not found when using jemalloc

### ISSUE THREAD

**Issue by superdolt** [taosdata/TDengine#7371]
1. autogen.sh not found when using jemalloc
2. under what circumstances advisable to use jemalloc instead of glibc?

**Comment by sangshuduo** [comment]
>     1. autogen.sh not found when using jemalloc
> 
>     2. under what circumstances advisable to use jemalloc instead of glibc?

README mention following steps:


First of all, you may clone the source codes from github:

git clone https://github.com/taosdata/TDengine.git
cd TDengine

The connectors for go & grafana have been moved to separated repositories, so you should run this command in the TDengine directory to install them:

git submodule update --init --recursive

Build TDengine
On Linux platform

mkdir debug && cd debug
cmake .. && cmake --build .

You can use Jemalloc as memory allocator instead of glibc:

apt install autoconf
cmake .. -DJEMALLOC_ENABLED=true

**Comment by fenghuazzm** [comment]
This issue was closed because it has been inactive for too many days.
