### ISSUE TITLE
a may-be NULL pointer dereference in TSDBJNIConnector.c

### ISSUE THREAD

**Issue by star-db-bugs** [taosdata/TDengine#8233]
**Bug Description**
In src/client/src/TSDBJNIConnector.c: Java_com_taosdata_jdbc_TSDBJNIConnector_fetchBlockImp(), line 659,
"int bytes = fields[i].bytes;"
, there is a 'fields' variable, which, however, is initialized by
"TAOS_FIELD *fields = taos_fetch_fields(tres);"
, while taos_fetch_fields() function can return NULL value.

This is first reported by my automatic tool. Please answer me whether I am wrong. Looking forward to your reply.

**Comment by sangshuduo** [comment]
Since the code is continuously changed, seems there is no such line, and the pointer determination mechanism is not necessary as the number of fields is checked. 

Let me close his issue and welcome to report a new one if you think there are other potential vulnerabilities.

Curious about what the tool you use is and good to know if it can be shared with us.
