### ISSUE TITLE
type cast error

### ISSUE THREAD

**Issue by rainingshining** [taosdata/TDengine#9842]
**Bug Description**
com.taosdata.jdbc.rs.RestfulResultSet, at line 264, @return row.getTimestamp(colIndex); return result should be casted to TimeStamp,
or error will occur;

while i created another class with the same name and path, cast return result into TimeStamp, it works fine;

I get jar from maven central, details as follow:
        
        <dependency>
            <groupId>com.taosdata.jdbc</groupId>
            <artifactId>taos-jdbcdriver</artifactId>
            <version>2.0.36</version>
        </dependency>

version of fastjson is 1.2.79, the latest version.

pic is as follow:
![图片](https://user-images.githubusercontent.com/52462960/149716173-55f35e59-262f-4df7-bcd2-81edb9a90a90.png)

**Comment by huolibo** [comment]
thank you for your issue. We've seen this problem recently. 
"getTimestamp(index)" API is incompatible because fastjson adapters to java9+  modularity [the return value changes from timestamp to object](https://github.com/alibaba/fastjson/pull/3878).
We have modified the code to cast object to timestamp in the "develop" branch。[change to timestamp](https://github.com/taosdata/TDengine/blob/develop/src/connector/jdbc/src/main/java/com/taosdata/jdbc/rs/RestfulResultSet.java#L271)。
You can compile it yourself if necessary, using `mvn clean package -Dmaven.test.skip=true`
