### ISSUE TITLE
how to taosdump data from 2.2.10.0 to 2.4.0.4?

### ISSUE THREAD

**Issue by YuMiaoPy** [taosdata/TDengine#9980]
### question of taosdump use 
I  backup database with taos version of 2.2.10.0. output Data as below.
<img width="325" alt="微信截图_20220123232339" src="https://user-images.githubusercontent.com/40236700/150685704-7130bd23-88c2-42a4-934e-3bec868dc687.png">
Then I try to restore this database with taos version of 2.4.0.4. But failed. Maybe avro codec is different.
![image](https://user-images.githubusercontent.com/40236700/150685831-60556629-dd55-4f82-918d-1119c2e870d0.png)

**Comment by sangshuduo** [comment]
taosdump depends on a new API provided by TDengine 2.4 and no more support SQL file due to SQL format can't store data correct for some cases. So please use new taosdump int the taosTools package with 2.4 and above only.
For the SQL file you dumped, you can use the taos shell command “taos -f xxx.sql" to restore them into new 2.4 instance.

**Comment by YuMiaoPy** [comment]
Thank you!
